### ISSUE TITLE
Reviewer 1 - Documentation

### ISSUE THREAD

**Issue by ksielemann** [BioMeCIS-Lab/OpenOmics#159]
* openOmics version: 0.8.6
* Python version: 3.9
* Operating System: Linux

### Description

It is not completely clear what OpenOmics can be specifically used for. An overview of the available functions and methods would be great: What exactly does OpenOmics do? What are specific usage examples (also e.g. after using OpenOmics: What's next?)?:

'OpenOmics facilitates the common coding tasks when preparing data for bioinformatics analysis.': For which bioinformatic analyses exactly?

This should be included in the README file.

**Comment by ksielemann** [comment]
An overview of all methods and functions of the package would be helpful.

**Comment by JonnyTran** [comment]
> 'OpenOmics facilitates the common coding tasks when preparing data for bioinformatics analysis.': For which bioinformatic analyses exactly?

The statement of need was written to be more general since I intended openomics to handle data wrangling tasks for *any* bioinformatics analysis that involve tabular-structured data. I just edited the package description on the `readme.md` to be a little more specific:

    This Python package provide a series of tools to integrate and query the genomics, transcriptomics, proteomics, and
    clinical data (aka multi-omics data). With scalable data-frame manipulation tools, OpenOmics facilitates the common
    data wrangling tasks when preparing data for RNA-seq bioinformatics analysis.

> An overview of all methods and functions of the package would be helpful.

On the RTD documentations, I've compiled the API Reference sections for browsing the classes and functions for various submodules in openomics. Although I haven't written a guide on the overview of different classes or docstrings for every modules and functions yet, I think (this directory)[https://openomics.readthedocs.io/en/latest/modules/openomics.multiomics.html] should give an overview over all the submodules of the package.

**Comment by ksielemann** [comment]
Thank you for your quick reply!

I definitely like the package description and the documentations better now. The usage examples are good the way they are now. So these comments are all addressed in my opinion! 

There is still one more issue with the tutorial 'Preparing data for downstream analyses':

To prepare the data for classification
```
# This function selects only patients with patholotic stages "Stage I" and "Stage II"
X_multiomics, y = luad_data.load_dataframe(,,
```
SyntaxError: invalid syntax (<string>, line 1)

**Comment by JonnyTran** [comment]
Hi @ksielemann thanks for pointing this out. I've just fixed the vignette at https://openomics.readthedocs.io/en/latest/usage/preprocess-downstream-analysis.html#to-prepare-the-data-for-classification

Honestly this usage guide (and a few others) do need an update since a lot of the underlying functionalities has been changed since they were written. I also have plan to add more key functionalities in the near future, so the guides will be rudimentary until those features have been implemented.

**Comment by ksielemann** [comment]
I think it is really important for future users that the usage guide works without errors. Otherwise, the user might get frustrated and refrains from using the library. So the usage guide should be updated according to the functionalities and current version of the package. But I think this can also happen while the package is further developed.

**Comment by JonnyTran** [comment]
Yes, I agree with that wholeheartedly. Will try my best to update them!
