### ISSUE TITLE
Reviewer 1 - Installation

### ISSUE THREAD

**Issue by ksielemann** [BioMeCIS-Lab/OpenOmics#161]
* openOmics version: -
* Python version: 3.9
* Operating System: Linux/Windows

### Description

Installation with `pip install openomics` worked fine on the Linux system I am using. However, using my windows computer, I got the following error: error: Microsoft Visual C++ 14.0 is required, but I cannot find this in the requirements

`from openomics import MultiOmics` results in the "UserWarning: Tensorflow not installed; ParametricUMAP will be unavailable"

**Comment by JonnyTran** [comment]
Hi @ksielemann. I think this issue could be due to the old `requirements.txt` that required UMAP, which somehow needs tensorflow dependency. So, since v0.8.5, I've fixed it by removing UMAP as it wasn't used in openomics.

Can you check if your github repository is updated to the latest @master branch, and `pip install --upgrade ./ -e` to update if it isn't? Let me know if the warning still persists when importing the package on your Windows OS.

**Comment by ksielemann** [comment]
Thanks! This works great now.
